-- [V] Sequence : 순차번호 생성기. 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ
    START WITH 1     -- 1부터 생성(기본값:1)
    INCREMENT BY 1   -- 1씩 증가(기본값:1)
    MAXVALUE 9999    -- 최대값
    -- MINVALUE -9999-- 최소값
    NOCYCLE          -- (Default : CYCLE)
    NOCACHE;         -- 캐시메모리를 사용 안 함(Default:CACHE)
SELECT 193+5 FROM EMP;  -- 198을 14번을 출력
SELECT 193+5 FROM DUAL; --오라클에서 제공하는 더미테이블
SELECT * FROM DUAL;     -- DUMMY : X
SELECT FRIEND_SQ.NEXTVAL FROM DUAL;  -- NEXTVAL(순차번호생성)
SELECT FRIEND_SQ.CURRVAL FROM DUAL;  -- CURRVAL(현재까지 진행된 순차번호)

-- ex. 시퀀스를 이용한 FRIEND테이블 
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
  NO   NUMBER(5) PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL,
  TEL  VARCHAR2(20) UNIQUE,
  ADDRESS VARCHAR2(255),
  LAST_MODIFY DATE DEFAULT SYSDATE
);
DROP SEQUENCE FRIEND_SQ;
CREATE SEQUENCE FRIEND_SQ  MAXVALUE 99999 NOCYCLE NOCACHE;      

INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
  VALUES(FRIEND_SQ.NEXTVAL, '홍길동',NULL, '신림');  -- 여러 번 실행 가능
SELECT NO,NAME,TEL,ADDRESS,TO_CHAR(LAST_MODIFY,'RR/MM/DD AM HH:MI:SS') LAST_MODIFY FROM FRIEND;
INSERT INTO FRIEND 
   VALUES(FRIEND_SQ.NEXTVAL, '김길동','010-9999-9999', '봉천','25/11/18');

DROP TABLE MEMBER_LEVEL; -- CASCADE CONSTRAINTS; 순서 바뀌어도 되나 비추
DROP TABLE MEMBER;
DROP SEQUENCE MEMBER_MNO_SQ;
CREATE TABLE MEMBER_LEVEL(
  LEVELNO NUMBER(1) PRIMARY KEY,
  LEVELNAME VARCHAR2(20) NOT NULL
);
INSERT INTO MEMBER_LEVEL VALUES(-1,'black');
INSERT INTO MEMBER_LEVEL VALUES(0,'일반');
INSERT INTO MEMBER_LEVEL VALUES(1,'실버');
INSERT INTO MEMBER_LEVEL VALUES(2,'골드');
select * from member_level;

CREATE TABLE MEMBER(
  mNO NUMBER(4) PRIMARY KEY,
  mNAME VARCHAR2(20) NOT NULL,
  mPW   VARCHAR2(8)  NOT NULL, --mPW VARCHAR2(8) CHECK(LENGTH(MPW) BETWEEN 1 AND 8),
  mMAIL VARCHAR2(30) UNIQUE,
  mPOINT NUMBER(9) ,  
  mRDATE DATE DEFAULT SYSDATE,
  LEVELNO NUMBER(1) REFERENCES MEMBER_LEVEL(LEVELNO)
);

CREATE SEQUENCE MEMBER_MNO_SQ MAXVALUE 9999 NOCYCLE NOCACHE;

INSERT INTO MEMBER 
  VALUES(MEMBER_MNO_SQ.NEXTVAL, '홍길동','aa','hong@hong.com',0,
        SYSDATE,0);
INSERT INTO MEMBER 
  VALUES(MEMBER_MNO_SQ.NEXTVAL, '신길동','bb','sin@sin.com',1000,
        '22/04/01',1);
SELECT mNO,mNAME, TO_CHAR(mRDATE,'YYYY-MM-DD') mRDATE,mMAIL,mPOINT point,
  levelname||'고객' LEVELNAME
  FROM MEMBER M, MEMBER_LEVEL L
  WHERE M.LEVELNO = L.LEVELNO
  ORDER BY mNO;







